#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.51.1.

use crate::username_registration::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_public_key_username_registration_impl(
    port_: MessagePort,
    namespace: impl Wire2Api<String> + UnwindSafe,
    public_key: impl Wire2Api<[u8; 32]> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "public_key_username_registration",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_namespace = namespace.wire2api();
            let api_public_key = public_key.wire2api();
            move |task_callback| {
                Ok(public_key_username_registration(
                    api_namespace,
                    api_public_key,
                ))
            }
        },
    )
}
fn wire_sign_as_username_registration_impl(
    port_: MessagePort,
    namespace: impl Wire2Api<String> + UnwindSafe,
    private_key: impl Wire2Api<[u8; 32]> + UnwindSafe,
    message: impl Wire2Api<Vec<u8>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "sign_as_username_registration",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_namespace = namespace.wire2api();
            let api_private_key = private_key.wire2api();
            let api_message = message.wire2api();
            move |task_callback| {
                Ok(sign_as_username_registration(
                    api_namespace,
                    api_private_key,
                    api_message,
                ))
            }
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
