/// Flutter icons ExtraAppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExtraAppIcons
///      fonts:
///       - asset: fonts/ExtraAppIcons.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ExtraAppIcons {
  ExtraAppIcons._();

  static const _kFontFam = 'ExtraAppIcons';
  static const String? _kFontPkg = null;

  static const IconData money = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_received = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_missed_outgoing = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_made = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_missed = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_split = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap_calls = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_merge = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_all = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content_copy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xf005, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xf029, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xf06b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill = IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xf328, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_alt = IconData(0xf3d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins = IconData(0xf51e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData greater_than = IconData(0xf531, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData greater_than_equal = IconData(0xf532, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData less_than = IconData(0xf536, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData less_than_equal = IconData(0xf537, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bill_wave = IconData(0xf53a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xf555, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_export = IconData(0xf56e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_import = IconData(0xf56f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
