// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_WEB_API_KEY"]!,
    appId: '1:871480363204:web:72ea28aeacd116e4492191',
    messagingSenderId: '871480363204',
    projectId: 'nautilus-a7345',
    authDomain: 'nautilus-a7345.firebaseapp.com',
    storageBucket: 'nautilus-a7345.appspot.com',
    measurementId: 'G-K2BCTV2J80',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_ANDROID_API_KEY"]!,
    appId: '1:871480363204:android:9e4022cb87c00946492191',
    messagingSenderId: '871480363204',
    projectId: 'nautilus-a7345',
    storageBucket: 'nautilus-a7345.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_IOS_API_KEY"]!,
    appId: '1:871480363204:ios:95b9c6a998425703492191',
    messagingSenderId: '871480363204',
    projectId: 'nautilus-a7345',
    storageBucket: 'nautilus-a7345.appspot.com',
    iosClientId: '871480363204-bd20vmid7gk577hkioua0124o9g1ass5.apps.googleusercontent.com',
    iosBundleId: 'co.perish.nautilus',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_MACOS_API_KEY"]!,
    appId: '1:871480363204:ios:91fb1984a3dbbda2492191',
    messagingSenderId: '871480363204',
    projectId: 'nautilus-a7345',
    storageBucket: 'nautilus-a7345.appspot.com',
    iosClientId: '871480363204-2de9id8nj3eod5pip1g3l9erqvbjgahm.apps.googleusercontent.com',
    iosBundleId: 'co.perish.nautiluswallet',
  );
}
